# Generated by Django 3.1.7 on 2021-03-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set(),
        ),
    ]
