# Generated by Django 3.1.7 on 2021-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210307_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
