# Generated by Django 3.1.7 on 2021-03-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default='l', max_length=200),
            preserve_default=False,
        ),
    ]
