# Generated by Django 3.1.7 on 2021-03-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slogan', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='general_settings/')),
                ('footer_text', models.CharField(max_length=200)),
                ('base_color', models.CharField(help_text='Enter color code', max_length=100)),
            ],
        ),
    ]
