# Generated by Django 3.1.7 on 2021-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0004_generalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='faveicon',
            field=models.ImageField(default='a', upload_to='general_settings/'),
            preserve_default=False,
        ),
    ]
