# Generated by Django 3.1.7 on 2021-03-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
            ],
        ),
    ]
